name = input("Enter your name: ")
age = input("Enter your age: ")
print(f"Hello, {name}! You are {age} years old.")
print ("Dame un numero: ")
numero1 = input()
print ("Dame otro numero: ")
numero2 = input()
suma = int(numero1) + int(numero2)
print (f"La suma de {numero1} + {numero2} es: {suma}")
